### ISSUE TITLE
Allow retries in subprocess commands

### ISSUE THREAD

**Issue by michael-sbarra-apexai** [ApexAI/rules_ros#21]
In the middle of `bazel run @rules_ros//repos/config:repos_lock.update`, network failures can occur:

```log
Traceback (most recent call last):
  File "/home/michael.sbarra/ade-home/.cache/bazel/_bazel_michael.sbarra/2786ee1af01eb601cf49528fecac940f/execroot/rules_ros/bazel-out/k8-fastbuild/bin/repos/config/detail/repos_lock.update.runfiles/rules_ros/repos/config/detail/lock_repos.py", line 133, in <module>
    main()
  File "/home/michael.sbarra/ade-home/.cache/bazel/_bazel_michael.sbarra/2786ee1af01eb601cf49528fecac940f/execroot/rules_ros/bazel-out/k8-fastbuild/bin/repos/config/detail/repos_lock.update.runfiles/rules_ros/repos/config/detail/lock_repos.py", line 49, in main
    additional_attributes = fetch_dependency_details(use_tar = args.tar, **spec)
  File "/home/michael.sbarra/ade-home/.cache/bazel/_bazel_michael.sbarra/2786ee1af01eb601cf49528fecac940f/execroot/rules_ros/bazel-out/k8-fastbuild/bin/repos/config/detail/repos_lock.update.runfiles/rules_ros/repos/config/detail/lock_repos.py", line 60, in fetch_dependency_details
    return fetch_git_details(type = type, **kwargs)
  File "/home/michael.sbarra/ade-home/.cache/bazel/_bazel_michael.sbarra/2786ee1af01eb601cf49528fecac940f/execroot/rules_ros/bazel-out/k8-fastbuild/bin/repos/config/detail/repos_lock.update.runfiles/rules_ros/repos/config/detail/lock_repos.py", line 115, in fetch_git_details
    raise ValueError(result.stderr)
ValueError: error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 10 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

It should auto-retry a max number of times (ie 3) before hard failing.

**Comment by michael-sbarra-apexai** [comment]
Implemented in #22
